name: workflow call
on: push
jobs:
   dummy_workflow:
     runs-on: ubuntu-latest
     steps:
      - name: Test
        run: |
            echo "hello world"
            echo " Dispatch URL: https://api.github.com/repos/amansunny08/dispatch_test/actions/workflows/dispatch_test/dispatches"  >> $GITHUB_STEP_SUMMARY

      - name: dummy_dispatch 
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
              github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: "dispatch_test",
                ref: "main",
                workflow_id: "dispatch.yaml",
                });

   dummy_Third_workflow1:
      needs: dummy_workflow
      uses: ./.github/workflows/call_workflow.yaml     

   summary_job: 
      needs: dummy_Third_workflow1
      uses: ./.github/workflows/summary.yaml