name: workflow call
on: push
jobs:
   dummy_workflow:
     runs-on: ubuntu-latest
     steps:
      - name: Test
        run: |
            echo "hello world"
            echo " Dispatch URL: https://api.github.com/repos/amansunny08/dispatch_test/actions/workflows/dispatch_test/dispatches"  >> $GITHUB_STEP_SUMMARY

      - name: dummy_dispatch 
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
              github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: "dispatch_test",
                ref: "main",
                workflow_id: "dispatch.yaml",
                });
                

      # - name: get dispatch result
      #   run: |
      #      ID=$(curl -L \
      #       -X POST \
      #       -H "Accept: application/vnd.github+json" \
      #       -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}"\
      #       -H "X-GitHub-Api-Version: 2022-11-28" \
      #       https://api.github.com/repos/amansunny08/dispatch_test/actions/workflows/dispatch.yaml/dispatches \
      #       -d '{"ref":"main"}')
      #      echo $ID >> $GITHUB_STEP_SUMMARY
           
      #      curl -X GET \
      #       -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
      #        https://api.github.com/repos/amansunny08/dispatch_test/actions/workflows   >> $GITHUB_STEP_SUMMARY
              
          # # https://api.github.com/repos/amansunny08/dispatch_test/actions/runs/5069590586 >> $GITHUB_STEP_SUMMARY
          #  curl -X POST \
          #   -H "Authorization: ${{ secrets.GH_TOKEN }}" \
          #   -H "Content-Type: application/json" \
          #   -d '{"ref":"YOUR_BRANCH_NAME"}' \
          #   https://api.github.com/repos/amansunny08/dispatch_test/actions/workflows/dispatch.yaml/dispatches

          #  curl -X GET \
          #     -H "Authorization: Bearer YOUR_ACCESS_TOKEN" \
          #     https://api.github.com/repos/YOUR_USERNAME/YOUR_REPO/actions/runs/YOUR_WORKFLOW_RUN_ID

  #  dummy_Third_workflow1:
  #     needs: dummy_workflow
  #     uses: ./.github/workflows/call_workflow.yaml     

  #  summary_job: 
  #     needs: dummy_workflow
  #     uses: ./.github/workflows/summary.yaml