name: workflow call
on: push
jobs:
   dummy_workflow:
     runs-on: ubuntu-latest
     steps:
     - name: hello world
       run: echo "hello world"

  #  dummy_Third_workflow1:
  #     needs: dummy_workflow
  #     uses: ./.github/workflows/third.yaml

   summary_job: 
      needs: dummy_workflow
      uses: ./.github/workflows/call.yaml