name: workflow call
on: push
jobs:
   dummy_workflow:
     runs-on: ubuntu-latest
     steps:
     - name: Test
       run: |
           echo "hello world"
           echo " Dispatch URL: https://api.github.com/repos/${{ github.repository }}/actions/workflows/dispatch_test/dispatches"  >> $GITHUB_STEP_SUMMARY

     - name: dummy_dispatch 
       run: |
          curl \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/dispatch_test/dispatches" 

   dummy_Third_workflow1:
      needs: dummy_workflow
      uses: ./.github/workflows/third.yaml

  #  Dummy_workflow_dispatch:
  #      needs: dummy_Third_workflow1
  #      run: |
  #         curl \
  #           -X POST \
  #           -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
  #           -H "Accept: application/vnd.github.v3+json" \
  #           "https://api.github.com/repos/${{ github.repository }}/actions/workflows/{workflow_id}/dispatches"

   summary_job: 
      needs: dummy_Third_workflow1
      uses: ./.github/workflows/call.yaml